import Fetchain from './index.js';

export default Fetchain;

export const { METHODS } = Fetchain;

export const { acl } = Fetchain;
export const { bind } = Fetchain;
export const { checkout } = Fetchain;
export const { connect } = Fetchain;
export const { copy } = Fetchain;
const { delete: _delete } = Fetchain;
export { _delete as delete };
export const { get } = Fetchain;
export const { head } = Fetchain;
export const { link } = Fetchain;
export const { lock } = Fetchain;
export const { merge } = Fetchain;
export const { mkactivity } = Fetchain;
export const { mkcalendar } = Fetchain;
export const { mkcol } = Fetchain;
export const { move } = Fetchain;
export const { notify } = Fetchain;
export const { options } = Fetchain;
export const { patch } = Fetchain;
export const { post } = Fetchain;
export const { propfind } = Fetchain;
export const { proppatch } = Fetchain;
export const { purge } = Fetchain;
export const { put } = Fetchain;
export const { rebind } = Fetchain;
export const { report } = Fetchain;
export const { search } = Fetchain;
export const { source } = Fetchain;
export const { subscribe } = Fetchain;
export const { trace } = Fetchain;
export const { unbind } = Fetchain;
export const { unlink } = Fetchain;
export const { unlock } = Fetchain;
export const { unsubscribe } = Fetchain;
